### PR TITLE
Add HSS as kernel extension

### PR DESCRIPTION
**Pull request by dberliner**
Due to the way Buildroot requires kernel changes to be structures this must be placed in this repo. We want to upstream the other repos anyways so I'm open to moving everything here as well.

### CODE REVIEW

**Review by drbild — COMMENTED** [review]
> Due to the way Buildroot requires kernel changes to be structures this must be placed in this repo.

Can you elaborate on this?  

According to the Buildroot docs, Linux kernel extensions can be included in external trees:

> #### Additional Linux kernel extensions
> 
> Additional Linux kernel extensions (see Section 17.21.2, “linux-kernel-extensions”) can be added by storing them in the linux/ directory at the root of a br2-external tree.

For us (for now), I think that approach would be simpler than maintaining these in-tree changes.

**Comment by dberliner** [comment]
I missed that in the docs, I would prefer to keep it all in the external tree for now so I'll make the switch.

**Comment by dberliner** [comment]
Looks like this feature as added in `2019.11` and we are at `2019.08`. For the time being this change needs to be here, we can upgrade Buildroot but that's a separate task that could introduce its own issues.

**Review by drbild — APPROVED** [review]
> Looks like this feature as added in `2019.11` and we are at `2019.08`. For the time being this change needs to be here, we can upgrade Buildroot but that's a separate task that could introduce its own issues.

Bummer, but the right call.

**Pull request merged**
